import {Oswald, Roboto} from "next/font/google";
import "./globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ["400", "700"]
})

const oswald = Oswald({
    variable: "--font-oswald",
    subsets: ["latin"],
    weight: ["400", "700"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function LocaleLayout({children, params}) {
    const {locale} = await params;
    // console.log(locale) // перевірочка
    if(!hasLocale(routing.locales, locale)) {
        notFound()
    }

    const messages = await getMessages({locale});
    // console.log(messages) // перевірочка

    return (
        <html lang={locale}>
            <body className={`${roboto.variable} ${oswald.variable} antialiased`}>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    )
}